#!/bin/bash
clear

directory=$1
moduleName=$0

echo "NKLocalizer"
echo "© Created by Nick Kopilovskii https://github.com/nkopilovskii/NKLocalizerTemplate"
echo

readonly DATE=`date +%d.%m.%Y`

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/Localizer"

function generateTemplates () {
  echo "Please enter type name ~>"
  read typeName

  localizerName="${typeName}Localizer"

  cd $(cd $directory; pwd) && mkdir $localizerName && cd $localizerName
  cp -R $SCRIPT_DIR/*.* $PWD

  for i in *.swift ; do
    mv $i `echo "$i"|awk -F'.' '{print "'$typeName'"$1"."$2}'`
    sed -i '' 's/$TYPE_NAME/'$typeName'/g' *.*
    sed -i '' 's/$CREATE_DATE/'$DATE'/g' *.*
    sed -i '' 's/$USER/'$USER'/g' *.*
  done


  for i in *.strings ; do
    mv $i `echo "$i"|awk -F'.' '{print "'$typeName'."$2}'`
    sed -i '' 's/$TYPE_NAME/'$typeName'/g' *.*
    sed -i '' 's/$CREATE_DATE/'$DATE'/g' *.*
    sed -i '' 's/$USER/'$USER'/g' *.*
  done

  echo
  echo
  echo "~Templates created~"
  echo
  echo
  askContinue
}

function enterDirectory () {
  echo "Please enter directory path ~> "
  read directory

  if [[ -d $directory ]]; then
  echo
  generateTemplates
  else
    echo "~Invalid directory!~"
    enterDirectory
  fi
}

function askContinue () {
  read -r -p "Do you want continue? [Yes/No] " response
  case "$response" in
    [yY][eE][sS]|[yY])
        cd ..
        generateTemplates
        ;;
    *)

    echo
    echo
    echo "Thank You & Good Luck!"  ;;
esac
}


enterDirectory

exit 0
